[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.5.6"
mouse-rs = "0.4"

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json"]

